### ISSUE TITLE
Add a comparison for flat_map

### ISSUE THREAD

**Issue by sshaw** [mooreniemi/array_collapse#1]
Would be interesting to see how it compares to this method.

**Comment by mooreniemi** [comment]
@sshaw because `flat_map` and `collapse` wont have the same outputs for the same inputs, it's not occurring to me off the top of my head what cases are worth comparing. 

perhaps an array nested only one deep, with no nils? i think that's the only fair comparison. 

if you can provide a case you'd like to see specifically, i'd be happy to graph it out though!

**Comment by sshaw** [comment]
Ah yes, I see. My mistake.
